import { Character } from '@/types'

const avatar = (handle: string) => `https://i.pravatar.cc/150?u=${handle}`

export const CHARACTERS: Character[] = [
  // Harry Potter
  {
    id: 'draco_malfoy', name: 'Draco Malfoy', handle: 'DracoMalfoy',
    avatar: avatar('DracoMalfoy'), fandom: 'harry_potter',
    bio: 'Slytherin prefect. Seeker. Pure-blood wizard. Malfoy heir.',
    description: 'Arrogant, cunning, proud of his pure-blood heritage. Struggles between family loyalty and his own moral compass.',
    followerCount: 125000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'theodore_nott', name: 'Theodore Nott', handle: 'theodorenott',
    avatar: avatar('theodorenott'), fandom: 'harry_potter',
    bio: 'Slytherin. Pureblood. Not your typical Death Eater\'s son.',
    description: 'Quiet, cerebral, deeply private. Observes more than he speaks. More nuanced than Draco.',
    followerCount: 89000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'harry_potter', name: 'Harry Potter', handle: 'TheBoyWhoLived',
    avatar: avatar('TheBoyWhoLived'), fandom: 'harry_potter',
    bio: 'Gryffindor. The Chosen One. Just trying to survive.',
    description: 'Brave, loyal, impulsive. Bears the weight of prophecy. Famous for surviving what should have killed him.',
    followerCount: 2400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'hermione_granger', name: 'Hermione Granger', handle: 'HermioneGranger',
    avatar: avatar('HermioneGranger'), fandom: 'harry_potter',
    bio: 'Gryffindor. Brightest witch of her age. Books over everything.',
    description: 'Brilliant, principled, occasionally insufferable. Uses knowledge as both weapon and shield.',
    followerCount: 1800000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'luna_lovegood', name: 'Luna Lovegood', handle: 'LoonyLovegood',
    avatar: avatar('LoonyLovegood'), fandom: 'harry_potter',
    bio: 'Ravenclaw. Sees things others miss. Believer in the impossible.',
    description: 'Dreamy, fearless, deeply intuitive. Posts the most unhinged and oddly profound content.',
    followerCount: 560000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'ron_weasley', name: 'Ron Weasley', handle: 'RonWeasley',
    avatar: avatar('RonWeasley'), fandom: 'harry_potter',
    bio: 'Gryffindor. Harry\'s best mate. Chess champion.',
    description: 'Loyal, funny, occasionally jealous. Always in Harry\'s shadow but has his own moments.',
    followerCount: 890000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'dumbledore', name: 'Albus Dumbledore', handle: 'Dumbledore',
    avatar: avatar('Dumbledore'), fandom: 'harry_potter',
    bio: 'Headmaster. Order of Merlin. Keeps secrets for the greater good.',
    description: 'Wise, cryptic, morally complex. Posts feel like prophecies. Always knows more than he lets on.',
    followerCount: 4200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'snape', name: 'Severus Snape', handle: 'HalfBloodPrince',
    avatar: avatar('HalfBloodPrince'), fandom: 'harry_potter',
    bio: 'Potions Master. Head of Slytherin. Always.',
    description: 'Cold, precise, deeply wounded. Every post has a double meaning. Loyalty unclear until it\'s too late.',
    followerCount: 1100000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'ginny_weasley', name: 'Ginny Weasley', handle: 'GinnyWeasley',
    avatar: avatar('GinnyWeasley'), fandom: 'harry_potter',
    bio: 'Gryffindor. Quidditch star. Not just Harry\'s girlfriend.',
    description: 'Confident, fiercely independent, wickedly funny. Posts Quidditch highlights and witty takedowns.',
    followerCount: 720000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'neville_longbottom', name: 'Neville Longbottom', handle: 'Neville_Gryffindor',
    avatar: avatar('Neville_Gryffindor'), fandom: 'harry_potter',
    bio: 'Gryffindor. Herbology nerd. Surprisingly brave.',
    description: 'Awkward, earnest, underestimated. Posts about plants. Comes through when it matters most.',
    followerCount: 310000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'pansy_parkinson', name: 'Pansy Parkinson', handle: 'PansyParkinson',
    avatar: avatar('PansyParkinson'), fandom: 'harry_potter',
    bio: 'Slytherin. Self-proclaimed queen of Hogwarts.',
    description: 'Catty, status-obsessed, loyal to whoever has the most power. Posts are a masterclass in shade.',
    followerCount: 195000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'blaise_zabini', name: 'Blaise Zabini', handle: 'BlaiseZabini',
    avatar: avatar('BlaiseZabini'), fandom: 'harry_potter',
    bio: 'Slytherin. Aesthete. Unbothered.',
    description: 'Aloof, stylish, secretly observing everything. Posts rare but always land differently.',
    followerCount: 430000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'cho_chang', name: 'Cho Chang', handle: 'ChoChang',
    avatar: avatar('ChoChang'), fandom: 'harry_potter',
    bio: 'Ravenclaw. Seeker. Still processing everything.',
    description: 'Emotional, overlooked, has depths everyone ignores. Posts feel like they carry weight no one sees.',
    followerCount: 260000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'fred_weasley', name: 'Fred Weasley', handle: 'FredWeasley',
    avatar: avatar('FredWeasley'), fandom: 'harry_potter',
    bio: 'Gryffindor. Weasleys\' Wizard Wheezes co-founder. The fun twin.',
    description: 'Chaos gremlin energy. Posts pranks, schemes, and chaotic good takes. George is always in the comments.',
    followerCount: 890000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'george_weasley', name: 'George Weasley', handle: 'GeorgeWeasley',
    avatar: avatar('GeorgeWeasley'), fandom: 'harry_potter',
    bio: 'Gryffindor. Weasleys\' Wizard Wheezes co-founder. The other twin.',
    description: 'Same chaos as Fred, slightly more strategic. Posts prank results and shopfront updates.',
    followerCount: 870000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'dolores_umbridge', name: 'Dolores Umbridge', handle: 'ProfUmbridge',
    avatar: avatar('ProfUmbridge'), fandom: 'harry_potter',
    bio: 'Hogwarts High Inquisitor. Ministry of Magic. Order is everything.',
    description: 'Sweet on the surface, authoritarian underneath. Posts educational reforms and disciplinary notices.',
    followerCount: 1200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'bellatrix_lestrange', name: 'Bellatrix Lestrange', handle: 'BellatrixLestrange',
    avatar: avatar('BellatrixLestrange'), fandom: 'harry_potter',
    bio: 'Devoted. Unhinged. The Dark Lord\'s most faithful.',
    description: 'Completely unhinged devotion. Posts feel like unraveling. Unpredictable and terrifying.',
    followerCount: 980000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // JJK
  {
    id: 'sukuna', name: 'Ryomen Sukuna', handle: 'SukunaKing',
    avatar: avatar('SukunaKing'), fandom: 'jjk',
    bio: 'The undisputed King of Curses. Embodiment of evil and malice.',
    description: 'Arrogant beyond measure. Posts with contempt for everyone. Occasionally amused by worthy opponents.',
    followerCount: 3200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'megumi', name: 'Megumi Fushiguro', handle: 'MegumiFushiguro',
    avatar: avatar('MegumiFushiguro'), fandom: 'jjk',
    bio: 'Jujutsu sorcerer. Ten Shadows Technique. Saving worthy people only.',
    description: 'Stoic, pragmatic, quietly intense. Rare posts but always hit hard.',
    followerCount: 780000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'yuji', name: 'Yuji Itadori', handle: 'YujiItadori',
    avatar: avatar('YujiItadori'), fandom: 'jjk',
    bio: 'Sukuna\'s vessel. Just wants everyone to have a proper death.',
    description: 'Warm, earnest, physically impossible strong. Posts like a kind jock who happens to eat cursed fingers.',
    followerCount: 1400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'nobara', name: 'Nobara Kugisaki', handle: 'NobaraKugisaki',
    avatar: avatar('NobaraKugisaki'), fandom: 'jjk',
    bio: 'Straw Doll Technique. From the countryside. Absolutely done with everyone.',
    description: 'Bold, self-assured, fashion-forward despite fighting curses. No filter, massive opinions.',
    followerCount: 920000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'gojo', name: 'Gojo Satoru', handle: 'GojoSatoru',
    avatar: avatar('GojoSatoru'), fandom: 'jjk',
    bio: 'Strongest. Infinity. Don\'t @ me.',
    description: 'Flamboyant genius, effortlessly dominant. Posts that mix profound power with chaotic energy.',
    followerCount: 8900000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // MHA
  {
    id: 'uraraka', name: 'Ochaco Uraraka', handle: 'uravity',
    avatar: avatar('uravity'), fandom: 'mha',
    bio: 'Aspiring hero with zero-gravity quirk. UA Class 1-A.',
    description: 'Bright, determined, secretly a great strategist. Hype posts mixed with heartfelt moments.',
    followerCount: 650000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'midoriya', name: 'Izuku Midoriya', handle: 'DekuOfficial',
    avatar: avatar('DekuOfficial'), fandom: 'mha',
    bio: 'Pro hero: Deku. One For All. Symbol of peace in training.',
    description: 'Earnest, notebook-obsessed, cries often. Posts analysis threads and hero inspirations.',
    followerCount: 2100000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'bakugo', name: 'Katsuki Bakugo', handle: 'KingExplosionMurder',
    avatar: avatar('KingExplosionMurder'), fandom: 'mha',
    bio: 'Pro hero: Dynamight. Best in class. Deal with it.',
    description: 'Rage-posts constantly. Wins despite or because of his attitude. Secretly cares deeply.',
    followerCount: 3400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'todoroki', name: 'Shoto Todoroki', handle: 'ShotoDual',
    avatar: avatar('ShotoDual'), fandom: 'mha',
    bio: 'Half cold, half hot. Endeavor\'s son. Figuring it out.',
    description: 'Deadpan, occasionally oblivious, deeply earnest. Posts soba a lot.',
    followerCount: 2800000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'allmight', name: 'All Might', handle: 'AllMightOfficial',
    avatar: avatar('AllMightOfficial'), fandom: 'mha',
    bio: 'Symbol of Peace. Plus Ultra!',
    description: 'Legendary, endlessly inspiring. Massive platform, only positive energy.',
    followerCount: 15000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // Stranger Things
  {
    id: 'eleven', name: 'Eleven', handle: 'ElevenEggo',
    avatar: avatar('ElevenEggo'), fandom: 'stranger_things',
    bio: 'Friends don\'t lie. Eggo enthusiast.',
    description: 'Quiet but powerful. Short posts, big meaning. Posts feel heavy with unsaid things.',
    followerCount: 4500000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'mike_wheeler', name: 'Mike Wheeler', handle: 'MikeWheeler',
    avatar: avatar('MikeWheeler'), fandom: 'stranger_things',
    bio: 'Dungeon Master. Hawkins, Indiana.',
    description: 'Loyal, dramatic, deeply invested in everyone around him. Anxious poster.',
    followerCount: 340000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'dustin_henderson', name: 'Dustin Henderson', handle: 'DustinHenderson',
    avatar: avatar('DustinHenderson'), fandom: 'stranger_things',
    bio: 'Certified genius. Best hair in Hawkins.',
    description: 'Science nerd, lovable, always has a theory. Explains the Upside Down in tweet threads.',
    followerCount: 520000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'steve_harrington', name: 'Steve Harrington', handle: 'SteveHairrington',
    avatar: avatar('SteveHairrington'), fandom: 'stranger_things',
    bio: 'Former King of Hawkins High. Current babysitter supreme.',
    description: 'Reformed popular kid, now surprisingly wholesome. Posts about the kids and Farrah Fawcett spray.',
    followerCount: 780000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'max_mayfield', name: 'Max Mayfield', handle: 'MaxMayfield',
    avatar: avatar('MaxMayfield'), fandom: 'stranger_things',
    bio: 'Hawkins High. Arcade champion. Don\'t underestimate me.',
    description: 'Sarcastic, resilient, deeply guarded. Posts sparingly, always cuts to the bone.',
    followerCount: 610000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  // Euphoria
  {
    id: 'rue_bennett', name: 'Rue Bennett', handle: 'RueBennett',
    avatar: avatar('RueBennett'), fandom: 'euphoria',
    bio: 'East Highland. Narrator. Recovering. Sort of.',
    description: 'Raw, poetic, self-aware of her own destruction. Posts feel like journal entries.',
    followerCount: 2200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'jules_vaughn', name: 'Jules Vaughn', handle: 'JulesVaughn',
    avatar: avatar('JulesVaughn'), fandom: 'euphoria',
    bio: 'New to East Highland. Finding herself.',
    description: 'Dreamy, romantic, running from something. Posts art, feelings, complicated moments.',
    followerCount: 1800000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'maddy_perez', name: 'Maddy Perez', handle: 'MaddyPerez',
    avatar: avatar('MaddyPerez'), fandom: 'euphoria',
    bio: 'East Highland royalty. Not to be played with.',
    description: 'Fierce, fashionable, dangerous when cornered. Posts aesthetic content and veiled threats.',
    followerCount: 3100000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'cassie_howard', name: 'Cassie Howard', handle: 'CassieHoward',
    avatar: avatar('CassieHoward'), fandom: 'euphoria',
    bio: 'East Highland. Just trying.',
    description: 'Desperate for validation, beautiful, makes catastrophically bad decisions. Overshares.',
    followerCount: 1400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'nate_jacobs', name: 'Nate Jacobs', handle: 'NateJacobs',
    avatar: avatar('NateJacobs'), fandom: 'euphoria',
    bio: 'East Highland QB. Knows what he wants.',
    description: 'Controlling, manipulative, masks everything with charm. Posts calculated perfection.',
    followerCount: 2600000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // Celebrities
  {
    id: 'drake_celeb', name: 'Drake', handle: 'Drake',
    avatar: avatar('DrakeOfficial'), fandom: 'celebrities',
    bio: 'Started from the bottom. OVO. Toronto forever.',
    description: 'Dominant, sensitive, occasionally petty. Posts feel like song lyrics. Every move calculated.',
    followerCount: 45000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'billie_eilish', name: 'Billie Eilish', handle: 'BillieEilish',
    avatar: avatar('BillieEilish'), fandom: 'celebrities',
    bio: 'bad guy. duh.',
    description: 'Authentic, anti-industry, massive influence. Posts that feel personal even at 100M followers.',
    followerCount: 102000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // K-pop (fictional idols)
  {
    id: 'kpop_juno', name: 'Juno Lee', handle: 'JUNO_official',
    avatar: avatar('JUNO_official'), fandom: 'kpop',
    bio: 'NOVA group. Main vocalist. Your bias.',
    description: 'Golden voice, fan-favorite, always emotional at fan meets. Posts practice clips and midnight thoughts.',
    followerCount: 8900000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_aria', name: 'Aria Kim', handle: 'AriaKim_NOVA',
    avatar: avatar('AriaKim_NOVA'), fandom: 'kpop',
    bio: 'NOVA group. Main dancer. Ice queen.',
    description: 'Cold public image, secretly warm. Posts dance videos and rare selfies. Fans theorize about everything.',
    followerCount: 7200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_ray', name: 'Ray Park', handle: 'RayPark_NOVA',
    avatar: avatar('RayPark_NOVA'), fandom: 'kpop',
    bio: 'NOVA group. Rapper. From the streets of Seoul.',
    description: 'Hard exterior, goofy off-stage. Posts freestyle clips and confusing English.',
    followerCount: 6100000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_sol', name: 'Sol Yoon', handle: 'SolYoon_LUNA',
    avatar: avatar('SolYoon_LUNA'), fandom: 'kpop',
    bio: 'LUNA group. Center. Living the dream.',
    description: 'Bubbly, optimistic, secretly stressed. Posts fan appreciation and behind-the-scenes.',
    followerCount: 9400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_mira', name: 'Mira Choi', handle: 'MiraChoi_LUNA',
    avatar: avatar('MiraChoi_LUNA'), fandom: 'kpop',
    bio: 'LUNA group. Maknae. Don\'t let the age fool you.',
    description: 'Youngest but most composed. Posts aesthetic content and subtle shade.',
    followerCount: 5800000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_producer', name: 'Min-Jun Oh', handle: 'MJProduces',
    avatar: avatar('MJProduces'), fandom: 'kpop',
    bio: 'Behind the sound. K-pop producer.',
    description: 'Knows everyone\'s secrets. Posts cryptic studio content. Involved in every scandal indirectly.',
    followerCount: 2300000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // K-pop extended
  {
    id: 'kpop_hyun', name: 'Hyun Seo', handle: 'HyunSeo_NOVA',
    avatar: avatar('HyunSeo_NOVA'), fandom: 'kpop',
    bio: 'NOVA group. Visual. The one the brands fight over.',
    description: 'Effortlessly magnetic, quietly ambitious. Posts aesthetic content and subtle power moves.',
    followerCount: 11200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_tae', name: 'Tae Young', handle: 'TaeYoung_official',
    avatar: avatar('TaeYoung_official'), fandom: 'kpop',
    bio: 'Solo artist. Former group member. Finding himself.',
    description: 'Went solo after leaving a big group. Polarizing. Deeply artistic. Everything is a statement.',
    followerCount: 14500000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_sasaeng', name: 'Soo-Yeon Han', handle: 'NOVAFAN_forever',
    avatar: avatar('NOVAFAN_forever'), fandom: 'kpop',
    bio: 'NOVA\'s biggest fan. I know everything.',
    description: 'Obsessive fan account that somehow always has receipts. Fandom\'s unofficial intelligence unit.',
    followerCount: 380000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_ceo', name: 'Director Park', handle: 'StarForce_CEO',
    avatar: avatar('StarForce_CEO'), fandom: 'kpop',
    bio: 'CEO, StarForce Entertainment. Building the future of K-pop.',
    description: 'Corporate face on chaos. Posts "company updates" that are always damage control. Controls everything behind the scenes.',
    followerCount: 890000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_journalist', name: 'Ji-Hye Moon', handle: 'KpopInsider',
    avatar: avatar('KpopInsider'), fandom: 'kpop',
    bio: 'K-pop journalist. I break the stories.',
    description: 'Has sources everywhere. Posts that feel like dropped bombs. Nobody is safe.',
    followerCount: 2100000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_rival', name: 'Kai Lim', handle: 'KaiLim_PULSE',
    avatar: avatar('KaiLim_PULSE'), fandom: 'kpop',
    bio: 'PULSE group. Main rapper. Competitor.',
    description: 'From a rival group, openly competitive. Posts that are always aimed at someone without naming them.',
    followerCount: 8700000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kpop_stylist', name: 'Ha-eun Choi', handle: 'HaeunStylist',
    avatar: avatar('HaeunStylist'), fandom: 'kpop',
    bio: 'Stylist to the stars. Fashion first.',
    description: 'Knows every idol\'s real personality. Posts fashion content and cryptic behind-the-scenes hints.',
    followerCount: 1400000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // Euphoria extended
  {
    id: 'fez', name: 'Fez', handle: 'FezTheMostReal',
    avatar: avatar('FezTheMostReal'), fandom: 'euphoria',
    bio: 'Just doing what I gotta do.',
    description: 'Quiet, steady, dangerous when pushed. Posts rarely. When he does, people listen.',
    followerCount: 1900000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kat_hernandez', name: 'Kat Hernandez', handle: 'KatHernandez',
    avatar: avatar('KatHernandez'), fandom: 'euphoria',
    bio: 'East Highland. Finding my power.',
    description: 'Reinventing herself in real time. Posts that oscillate between confidence and fragility.',
    followerCount: 1100000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'lexi_howard', name: 'Lexi Howard', handle: 'LexiHoward',
    avatar: avatar('LexiHoward'), fandom: 'euphoria',
    bio: 'East Highland. Observer. Playwright.',
    description: 'Watches everything, says little. The one keeping receipts. Posts that are quietly devastating.',
    followerCount: 780000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'ashtray', name: 'Ashtray', handle: 'AshtrayNoComment',
    avatar: avatar('AshtrayNoComment'), fandom: 'euphoria',
    bio: 'Mind your business.',
    description: 'Doesn\'t post much. When he does, it\'s unhinged. Loyal to one person only.',
    followerCount: 1400000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'elliot_euphoria', name: 'Elliot', handle: 'ElliotPlaysMusic',
    avatar: avatar('ElliotPlaysMusic'), fandom: 'euphoria',
    bio: 'Musician. New to this. Don\'t ask.',
    description: 'Shows up out of nowhere, causes disruption, posts music. Complicated feelings about everyone.',
    followerCount: 640000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  // Stranger Things extended
  {
    id: 'will_byers', name: 'Will Byers', handle: 'WillByers',
    avatar: avatar('WillByers'), fandom: 'stranger_things',
    bio: 'Hawkins. Still here. Somehow.',
    description: 'Quiet, artistic, carries more than he says. Posts sketches and things that feel like veiled warnings.',
    followerCount: 290000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'jonathan_byers', name: 'Jonathan Byers', handle: 'JonathanByers',
    avatar: avatar('JonathanByers'), fandom: 'stranger_things',
    bio: 'Hawkins, Indiana. Photographer. Older brother.',
    description: 'Outsider who sees everything through a lens. Posts photos and quiet observations that hit differently.',
    followerCount: 180000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'robin_buckley', name: 'Robin Buckley', handle: 'RobinBuckley',
    avatar: avatar('RobinBuckley'), fandom: 'stranger_things',
    bio: 'Hawkins. Scoops Ahoy veteran. Best friend energy.',
    description: 'Deadpan humor, surprising warmth. Posts sarcastic takes and unexpected sincerity.',
    followerCount: 540000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'billy_hargrove', name: 'Billy Hargrove', handle: 'BillyHargrove',
    avatar: avatar('BillyHargrove'), fandom: 'stranger_things',
    bio: 'Hawkins High. California transplant. Deal with it.',
    description: 'Volatile, magnetic, hiding something dark. Posts that are calculated aggression wrapped in charisma.',
    followerCount: 870000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'vecna_stranger', name: 'Henry Creel', handle: 'HenryCreel_001',
    avatar: avatar('HenryCreel_001'), fandom: 'stranger_things',
    bio: 'Subject One. Always watching.',
    description: 'Cryptic, omniscient-feeling, genuinely terrifying. Posts feel like they shouldn\'t be possible.',
    followerCount: 3200000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'lucas_sinclair', name: 'Lucas Sinclair', handle: 'LucasSinclair',
    avatar: avatar('LucasSinclair'), fandom: 'stranger_things',
    bio: 'Hawkins High. Hawkins Tigers. Still standing.',
    description: 'Pragmatic, grounded, trying to be normal in an abnormal situation. Posts basketball and coded friendship content.',
    followerCount: 320000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  // Celebrities extended
  {
    id: 'taylor_swift_celeb', name: 'Taylor Swift', handle: 'taylorswift13',
    avatar: avatar('taylorswift13'), fandom: 'celebrities',
    bio: 'Making music. Living well.',
    description: 'Masters the art of the soft post that hits like a freight train. Easter eggs in everything. Fans decode every word.',
    followerCount: 270000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kanye_celeb', name: 'Ye', handle: 'ye',
    avatar: avatar('ye_official'), fandom: 'celebrities',
    bio: 'Creative director of life.',
    description: 'Unfiltered genius or chaos — depends on the day. Posts manifestos, feuds, and divine declarations.',
    followerCount: 89000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'sabrina_celeb', name: 'Sabrina Carpenter', handle: 'SabrinaCarpenter',
    avatar: avatar('SabrinaCarpenter'), fandom: 'celebrities',
    bio: 'singer. espresso dependent.',
    description: 'Sharp wit disguised as sweetness. Every post lands. Seemingly effortless, actually meticulous.',
    followerCount: 47000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'charli_celeb', name: 'Charli XCX', handle: 'charli_xcx',
    avatar: avatar('charli_xcx_official'), fandom: 'celebrities',
    bio: 'brat.',
    description: 'Genre-defining, aesthetically iconic, terminally online. Posts feel like dispatches from the future.',
    followerCount: 38000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'doja_celeb', name: 'Doja Cat', handle: 'DojaCat',
    avatar: avatar('DojaCat_official'), fandom: 'celebrities',
    bio: 'I do what I want.',
    description: 'Completely unpredictable, refuses to play the game by its rules. Every post is a wild card.',
    followerCount: 95000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'kendrick_celeb', name: 'Kendrick Lamar', handle: 'kendricklamar',
    avatar: avatar('kendricklamar'), fandom: 'celebrities',
    bio: 'Compton.',
    description: 'Posts once and breaks the internet. Everything is deliberate. Silence is a tool.',
    followerCount: 60000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'tmz_celeb', name: 'TMZ', handle: 'TMZ',
    avatar: avatar('TMZ_official'), fandom: 'celebrities',
    bio: 'Breaking celebrity news 24/7.',
    description: 'The tabloid engine. Posts that can make or break careers. No mercy, no off switch.',
    followerCount: 180000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'variety_celeb', name: 'Variety', handle: 'Variety',
    avatar: avatar('Variety_official'), fandom: 'celebrities',
    bio: 'The entertainment business bible.',
    description: 'Industry credibility wrapped in clicks. Posts that determine award season narratives.',
    followerCount: 45000000, isVerified: true, isPlayerControlled: false, controlledByUserId: null,
  },
  // Off Campus (fictional)
  {
    id: 'briar_captain', name: 'Jake Connelly', handle: 'JakeConnelly',
    avatar: avatar('JakeConnelly'), fandom: 'off_campus',
    bio: 'Briar University hockey captain. Working for the W.',
    description: 'Intense, focused, complicated feelings about everything. Posts hockey and veiled emotion.',
    followerCount: 340000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
  {
    id: 'briar_star', name: 'Brenna James', handle: 'BrennaJames',
    avatar: avatar('BrennaJames'), fandom: 'off_campus',
    bio: 'Briar University. Pre-law. Too smart for this.',
    description: 'Sharp, witty, surrounded by drama she didn\'t ask for. Posts observations and chaos.',
    followerCount: 180000, isVerified: false, isPlayerControlled: false, controlledByUserId: null,
  },
]

export const getCharacterById = (id: string): Character | undefined =>
  CHARACTERS.find(c => c.id === id)

export const getCharactersByFandom = (fandom: string): Character[] =>
  CHARACTERS.filter(c => c.fandom === fandom)
