import { Scenario } from '@/types'
import { CHARACTERS } from './characters'

const hp = (ids: string[]) => ids.map(id => CHARACTERS.find(c => c.id === id)!).filter(Boolean)

export const SCENARIOS: Scenario[] = [
  {
    id: 'celebrities',
    name: 'Celebrities',
    description: 'A shimmering, high-stakes arena where celebrity status is the only currency that matters. Every retweet is a social earthquake.',
    coverImage: 'https://i.pravatar.cc/400?u=celebrities_cover',
    category: '✨ Celebrities',
    fandom: 'celebrities',
    defaultCharacters: hp(['drake_celeb', 'billie_eilish']),
    defaultWorldSetting: 'A shimmering, high-stakes arena where celebrity status is the only currency that matters. Every retweet is a social earthquake and every post can ripple through the hierarchies of Hollywood power.',
    defaultMainGoal: 'Become the most iconic celebrity of your generation',
    playerCount: 12847,
  },
  {
    id: 'accidentally_famous',
    name: 'Accidentally Famous',
    description: 'One video blew up overnight. Now the entire internet knows your name. You didn\'t ask for this.',
    coverImage: 'https://i.pravatar.cc/400?u=accidentally_famous_cover',
    category: '✨ Celebrities',
    fandom: 'celebrities',
    defaultCharacters: hp(['billie_eilish', 'drake_celeb']),
    defaultWorldSetting: 'One video blew up overnight. Now the entire internet knows your name. You didn\'t ask for this. Now you have to figure out what to do with it.',
    defaultMainGoal: 'Turn accidental fame into a lasting career',
    playerCount: 8423,
  },
  {
    id: 'harry_potter',
    name: 'Harry Potter',
    description: 'Dark forces are rising. House rivalries are brutal. Life at Hogwarts plays out through the school feed.',
    coverImage: 'https://i.pravatar.cc/400?u=harry_potter_cover',
    category: '⚡ Harry Potter',
    fandom: 'harry_potter',
    defaultCharacters: hp(['draco_malfoy', 'harry_potter', 'hermione_granger', 'ron_weasley', 'luna_lovegood', 'snape', 'dumbledore', 'theodore_nott']),
    defaultWorldSetting: 'Dark forces are rising. House rivalries are brutal. Life at Hogwarts plays out through the school feed — breaking stories, Quidditch drama, forbidden corridor sightings, and Dumbledore\'s announcements getting more ominous every day.',
    defaultMainGoal: 'Win the House Cup and become a Hogwarts legend',
    playerCount: 34891,
  },
  {
    id: 'kpop_debut',
    name: 'K-Pop Idol: Debut Era',
    description: 'Your group just debuted. Survive the dating scandals, sasaeng fans, company politics, and fan wars.',
    coverImage: 'https://i.pravatar.cc/400?u=kpop_debut_cover',
    category: '🎤 K-pop',
    fandom: 'kpop',
    defaultCharacters: hp(['kpop_juno', 'kpop_aria', 'kpop_ray', 'kpop_sol', 'kpop_mira', 'kpop_producer']),
    defaultWorldSetting: 'Your group just debuted. Survive the dating scandals, sasaeng fans, company politics, and fan wars. Fame is a knife and you\'re holding the blade.',
    defaultMainGoal: 'Go from debut to daesang without losing yourself',
    playerCount: 19234,
  },
  {
    id: 'euphoria',
    name: 'Euphoria',
    description: 'East Highland is a mess. Everyone\'s beautiful, everyone\'s broken, and everyone\'s posting through it.',
    coverImage: 'https://i.pravatar.cc/400?u=euphoria_cover',
    category: '✨ Euphoria',
    fandom: 'euphoria',
    defaultCharacters: hp(['rue_bennett', 'jules_vaughn', 'maddy_perez', 'cassie_howard', 'nate_jacobs']),
    defaultWorldSetting: 'East Highland is a mess. Everyone\'s beautiful, everyone\'s broken, and everyone\'s posting through it. The parties never stop and neither does the damage.',
    defaultMainGoal: 'Survive East Highland with your soul intact',
    playerCount: 7823,
  },
  {
    id: 'off_campus',
    name: 'Off Campus',
    description: 'The Off-Campus universe at Briar University — the hockey team dominates campus attention.',
    coverImage: 'https://i.pravatar.cc/400?u=off_campus_cover',
    category: '🏫 Off Campus',
    fandom: 'off_campus',
    defaultCharacters: hp(['briar_captain', 'briar_star']),
    defaultWorldSetting: 'The Off-Campus universe at Briar University — the hockey team dominates campus attention, everyone has secrets, and the group chat is always on fire.',
    defaultMainGoal: 'Win the Frozen Four and the person you\'re not supposed to want',
    playerCount: 5621,
  },
  {
    id: 'singers_girlfriend',
    name: 'Singer\'s Girlfriend',
    description: 'Dating a global pop star means nothing is private.',
    coverImage: 'https://i.pravatar.cc/400?u=singers_girlfriend_cover',
    category: '✨ Celebrities',
    fandom: 'celebrities',
    defaultCharacters: hp(['billie_eilish', 'drake_celeb']),
    defaultWorldSetting: 'Dating a global pop star means nothing is private. His fans think they own him. His label thinks they own you. You\'re figuring out who you are in the middle of all of it.',
    defaultMainGoal: 'Build your own identity while navigating his world',
    playerCount: 11204,
  },
  {
    id: 'rappers_girlfriend',
    name: 'Rapper\'s Girlfriend',
    description: 'Your boyfriend\'s a rapper. Now his fans, his ex, and his lyrics are all about you.',
    coverImage: 'https://i.pravatar.cc/400?u=rappers_girlfriend_cover',
    category: '🎤 Rappers/Celebrities',
    fandom: 'rappers',
    defaultCharacters: hp(['drake_celeb', 'billie_eilish']),
    defaultWorldSetting: 'Your boyfriend\'s a rapper. Now his fans, his ex, and his lyrics are all about you. You didn\'t sign up for this but the cameras don\'t care.',
    defaultMainGoal: 'Survive the spotlight and come out stronger',
    playerCount: 9182,
  },
  {
    id: 'artist_of_year',
    name: 'Artist of the Year',
    description: 'Diss tracks at midnight, fan wars, leaked DMs, and one Grammy to rule them all.',
    coverImage: 'https://i.pravatar.cc/400?u=artist_of_year_cover',
    category: '✨ Celebrities',
    fandom: 'celebrities',
    defaultCharacters: hp(['drake_celeb', 'billie_eilish']),
    defaultWorldSetting: 'Diss tracks at midnight, fan wars, leaked DMs, and one Grammy to rule them all. The music industry is a war and you\'re in the middle of it.',
    defaultMainGoal: 'Win Artist of the Year and survive the fallout',
    playerCount: 14502,
  },
  {
    id: 'famous_rapper',
    name: 'Famous Rapper',
    description: 'You just got signed. Now turn clout into a legacy.',
    coverImage: 'https://i.pravatar.cc/400?u=famous_rapper_cover',
    category: '🎤 Rappers/Celebrities',
    fandom: 'rappers',
    defaultCharacters: hp(['drake_celeb', 'billie_eilish']),
    defaultWorldSetting: 'You just got signed. Now turn clout into a legacy. The streets are watching, the labels are circling, and one wrong move ends everything.',
    defaultMainGoal: 'Build a legendary rap career',
    playerCount: 7891,
  },
  {
    id: 'stream_for_fame',
    name: 'Stream for Fame',
    description: 'You\'re live and the internet is watching. One clip can end you or make you a legend.',
    coverImage: 'https://i.pravatar.cc/400?u=stream_for_fame_cover',
    category: '📺 YouTuber/Streamer',
    fandom: 'youtube',
    defaultCharacters: hp(['billie_eilish', 'drake_celeb']),
    defaultWorldSetting: 'You\'re live and the internet is watching. One clip can end you or make you a legend. The chat never sleeps.',
    defaultMainGoal: 'Hit 10 million subscribers and secure the bag',
    playerCount: 6234,
  },
  {
    id: 'heated_rivalry',
    name: 'Heated Rivalry',
    description: 'You\'re rivals. On the ice, you want to destroy each other.',
    coverImage: 'https://i.pravatar.cc/400?u=heated_rivalry_cover',
    category: '🔥 Heated Rivalry',
    fandom: 'off_campus',
    defaultCharacters: hp(['briar_captain', 'briar_star']),
    defaultWorldSetting: 'You\'re rivals. On the ice you want to destroy each other. Off it, it\'s complicated. The internet has picked sides and neither side is quiet.',
    defaultMainGoal: 'Dominate your rival and figure out your feelings',
    playerCount: 4821,
  },
  {
    id: 'stranger_things',
    name: 'Stranger Things',
    description: 'Vecna is back and Hawkins is falling apart. The Upside Down is leaking into the feed.',
    coverImage: 'https://i.pravatar.cc/400?u=stranger_things_cover',
    category: '🎮 Stranger Things',
    fandom: 'stranger_things',
    defaultCharacters: hp(['eleven', 'mike_wheeler', 'dustin_henderson', 'steve_harrington', 'max_mayfield']),
    defaultWorldSetting: 'Vecna is back and Hawkins is falling apart. The Upside Down is leaking into the feed. Some posts aren\'t from this dimension.',
    defaultMainGoal: 'Stop Vecna and save Hawkins before it\'s too late',
    playerCount: 9871,
  },
  {
    id: 'world_war_iii',
    name: 'World War III',
    description: 'Global powers on the brink. Social media is the new battlefield.',
    coverImage: 'https://i.pravatar.cc/400?u=world_war_iii_cover',
    category: '🗳️ Politics',
    fandom: 'politics',
    defaultCharacters: hp(['drake_celeb', 'billie_eilish']),
    defaultWorldSetting: 'Global powers on the brink. Social media is the new battlefield. Every post is propaganda, every like is allegiance, and silence is its own statement.',
    defaultMainGoal: 'Navigate the geopolitical crisis and shape the narrative',
    playerCount: 3421,
  },
]

export const getFeaturedScenarios = () => SCENARIOS.slice(0, 6)
export const getPopularScenarios = () => SCENARIOS.slice(6)
export const getScenarioById = (id: string) => SCENARIOS.find(s => s.id === id)
